### ISSUE TITLE
The website going down frequently

### ISSUE THREAD

**Issue by tnfssc** [himanshubhardwaz/himanshubhardwaz.com#1]
The website is going down frequently. Probably because `fly` machine is taking some time to spin your site up. Since this is static site, you can host it on a static CDN host like Cloudflare Pages or GitHub Pages. Using something like Cloudflare's Always Online might work too.

![image](https://github.com/user-attachments/assets/a86686cb-3ccd-4a04-950e-2bcfe5db357a)

**Comment by himanshubhardwaz** [comment]
It's live on Cloudflare Pages now. For some reason, Fly is automatically turning off the machine, despite the `min_machines_running = 1` flag, which used to work earlier on their hobby plan. It seems they might have changed that.
